### ISSUE TITLE
Add Switch to setting page for sandbox/Live

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#11]

**Comment by angelleye** [comment]
@tejasm-itpath I saw the check box for Sandbox in the settings, but even when it's not checked things are still hitting the sandbox.  You have this marked ready for review, though, so I would expect that if sandbox isn't enabled it should be hitting the live servers..??

**Comment by tejasm-itpath** [comment]
I had same question yesterday but I found the scenario , what actually happened is when user just installed plugin and haven't save settings then Nothing would be found in the wp option about the paypal environment.
So , For that condition ,  we can solve either following 2 ways
1) Either we give user to select environment first and then connect to PayPal.
2) By adding default sandbox while activate plugin.

I look in other paypal plugin of yours but they have not connect to paypal scenario so i have set default sandbox.

What's your opinion for this ?

**Comment by angelleye** [comment]
@tejasm-itpath I think I'd rather leave the default as live, but then use some jQuery to check the value of the toggle when the Connect to PayPal button is clicked.  If the toggle itself (not just the database value, which doesn't exist yet) is set to sandbox, then the Connect button should use sandbox.

Does that make sense?  Can we do that?
