### ISSUE TITLE
Take care of PHP timout while capturing Referance Transactions

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#14]

**Comment by angelleye** [comment]
@tejasm-itpath Please provide some details on what we've done here.  How is this handling situations where the user closes the browser after triggering the Fun Button?

**Comment by tejasm-itpath** [comment]
@angelleye 
Right now I have tested this issue by adding following code at the start of the function DoRefTransaction

> @set_time_limit(GW_PLUGIN_SET_TIME_LIMIT);
> @ignore_user_abort(true);

And I have added File write code under the foreach loop to test if it is work or not and I was just printing array in the file write. 
When I started Reference transaction and close browers, still file is writing and stops when execution complete.

**Comment by tejasm-itpath** [comment]
Right now I have removed File write code because we have to do that in a way plugin stores logs.
