### ISSUE TITLE
Create custom page for cancel url and erros  of the paypal express checkout

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#15]

**Comment by tejasm-itpath** [comment]
https://github.com/angelleye/GiveWhen/commit/e638439a3e168a3ff5023dbdc528958af184cacc

**Comment by tejasm-itpath** [comment]
@angelleye  
Still I need to add contents dynamically.

**Comment by angelleye** [comment]
@tejasm-itpath Not sure what you mean that you still need to contents dynamically..??  Are you referring to what will be displayed on the thank you page?  

So for this issue you simply setup the redirect to a blank page, and in a separate issue you'll be building out that page..??

**Comment by tejasm-itpath** [comment]
@angelleye  
I am thinking of Adding contents dynamically , For example : If user done Billing agreement Successfully with "Goal one" then I want to show message like "Thank you for signed up in Goal One"  and other information related to it.

Right now this  page is static , i want to find a way to add page content dynamically before page is redirecting

**Comment by angelleye** [comment]
@tejasm-itpath For the cancel page we can send the user back to the page they left from...the goal signup page.

We could do the same thing for the errors, and just show the error above the signup form.  That way they can easily try again if the error helps them.

**Comment by angelleye** [comment]
So I guess we'd have to build the check for an error and display it into the shortcode output for the signup form.  Might be cleaner to just go ahead and do a custom page template for the PayPal error, and then add a link to 'try again" that sends them back to the signup form page they came from.  We can discuss this together.
