### ISSUE TITLE
Delete user 

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#21]
we should tie in the ability to cancel the Billing Agreement if they're deleting a Giver, too
So when deleting the Giver record, if BAID exists (which is usually will)  pop up a message "Would you like to delete the Billing agreement on file with PayPal as well?"
If they say OK/Yes then we'll call BAUpdate to cancel the agreement
Alternatively, we could simply state "Deleting this Giver will also cancel their PayPal billing agreement."
And then just have options:  OK, Cancel

**Comment by angelleye** [comment]
When a user account is deleted, it will automatically cancel any open billing agreement on PayPal.  Need to document this.
