### ISSUE TITLE
After Referance Transaction process complete we will display total transactions, Total Amout and total Failed transactions

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#22]
While Doing transactions, we will display some sort of information display there at page

**Comment by angelleye** [comment]
To summarize...

- When you click the Fun Button, a console displays that returns the result of each individual transaction that is being processed while it runs.

- If you close the browser while it's running, the script will remain running on the server until it completes (this was done in another issue already.)

- If you watch all the way to the end, you will then see a report that outlines the total number of transactions attempted, the total number succeeded, and the total failed.

- Either way, whether you watch the whole process or not, you will receive an email with the same basic report info that gets displayed on screen at completion.
