### ISSUE TITLE
Fun Button processing result message adjustment.

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#27]
I ran a test with a single Giver in the system and the payment failed, however, I was still given a successful result message:

![image](https://user-images.githubusercontent.com/629241/27850559-22387c0a-611b-11e7-8af3-1335d8a5fccb.png)

We need to adjust this message based on the following:

- ALL transactions processed successfully - "You have successfully processed all payments for this goal." - green background.
- Some transactions completed, some failed - "You have partially processed all payments for this goal.  _x_ payments failed. - yellow background
- ALL transactions failed - "Payments could not be processed.  Please check error logs for more details." - red background

**Comment by tejasm-itpath** [comment]
This will be included in #22
