### ISSUE TITLE
PHP Warnings after updating to latest files.

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#36]
When I view the log tab in settings:  http://woo.angelleye.com/wp-admin/admin.php?page=give_when_option&tab=logs

I get this:

> Warning: scandir(/home/angelley/sandbox_woocommerce/wp-content/uploads/give-when-logs/): failed to open dir: No such file or directory in /home/angelley/sandbox_woocommerce/wp-content/plugins/angelleye-givewhen/admin/partials/class-give-when-log.php on line 103
> 
> Warning: scandir(): (errno 2): No such file or directory in /home/angelley/sandbox_woocommerce/wp-content/plugins/angelleye-givewhen/admin/partials/class-give-when-log.php on line 103
> 
> Warning: Invalid argument supplied for foreach() in /home/angelley/sandbox_woocommerce/wp-content/plugins/angelleye-givewhen/admin/partials/class-give-when-log.php on line 104

We need to make sure we're creating the directory that needs to exist for logs so that it shows up even if there aren't any logs yet.

**Comment by angelleye** [comment]
I did go ahead and enter my credentials, and I checked to save logs and then saved the settings thinking maybe it would go ahead and create the log folder at that time, but it didn't.  Still got the same warning when moving back to logs tab.

**Comment by tejasm-itpath** [comment]
@angelleye 
I have created log directories at the time of plugin activation, 
So just deactivate and activate the plugin , it will resolve your error. 
That's why I mentioned before to test plugin in Fresh wordpress haha, because I have made so many changes in last week.

**Comment by angelleye** [comment]
Yes, that worked, thanks.
