### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#44]
* ~~Still need to get API logs masked in the Log tab.~~
* ~~Under Connect to PayPal, currency should default to USD~~
* ~~Under WP -> Plugins, the GiveWhen plugin still has a space (ie. Give When) in the name.~~
* ~~When I was set on Sandbox, and I clicked Connect, it took me through the process, but then dropped me back on the settings page with Sandbox turned OFF, and it's telling me I'm connected live even though I'm not.~~
* ~~Need to make sure correct currency symbol displays on output based on currency code option in settings.~~
* ~~Add New Goal - Upload Image button should say Add Image instead.~~
* ~~Add New Goal - Tabbing from Title to other goal fields needs to be re-ordered.~~
* ~~After creating new goal - on click of shortcode value should select the whole short code (same as it does when I click the Copy button).~~
* ~~After creating new goal - The copy button works, but we need to add a notice that says "Shortcode is copied to your clipboard." after clicking it.~~
* ~~Shortcode drop down in New Page / Post needs to be adjusted.  It should still say "Shortcodes" and then under that we should have our GiveWhen sub-menu.  This way other plugins that also provide shortcodes would show up under the same Shortcodes menu.~~
* ~~On goal shortcode display as well as in preview, the output still has spacing issues, a colon, and needs dynamic currency symbol.~~
* ~~Preview needs to actually function when I change the amount (but does not need to function for the actual sign up)~~
* ~~Display of goal sign up form on front-end page/post is outputting the option value for fixed/select/manual and shouldn't be.~~
* ~~Sign up for needs to flow properly when users are signed in vs. not signed in.  This includes the option to create an account with the site during sign-up or not.~~
* ~~Add Overlay at the time of Connect With PayPal~~
* ~~Add **GiveWhen Transaction** menu in Wordpress Front End.~~
* ~~Amount instering Blank in the givewhen_sign_up post type~~
* ~~Thankyou page need to be better in design~~

**Comment by tejasm-itpath** [comment]
@angelleye 
I can not reproduce these two issue.
> Under Connect to PayPal, currency should default to USD

> When I was set on Sandbox, and I clicked Connect, it took me through the process, but then dropped me back on the settings page with Sandbox turned OFF, and it's telling me I'm connected live even though I'm not.

**Comment by tejasm-itpath** [comment]
@angelleye 
> Shortcode drop down in New Page / Post needs to be adjusted. It should still say "Shortcodes" and then under that we should have our GiveWhen sub-menu. This way other plugins that also provide shortcodes would show up under the same Shortcodes menu.
For above Task I have done some work on Tinymce but we can not merge all plugin's Shortcodes into the one dropdown. as we have to register fields in tinymec js . But we can merge Shortcodes of our own plugins Like PayPal Button Manager and GiveWhen into one Dropdown.

**Comment by tejasm-itpath** [comment]
@angelleye 
> Sign up for needs to flow properly when users are signed in vs. not signed in. This includes the option to create an account with the site during sign-up or not.

I have changed the flow of signed up as User will be created after successful response of  Billing agreement.
but Guest user signup is still on hold as I have created new role as GuestGiver and  I am managing users based on that.

**Comment by tejasm-itpath** [comment]
@angelleye 
> Error at the time of Bulk Delete Givers

I got Error at the time of Bulk delete of the user and we are also doing Cancel Billing Agreement on delete_user action so we have to find a way where we can fetch multiple users id on the delete_user action

**Comment by angelleye** [comment]
@tejasm-itpath For the shortcodes, let's simplify.  The drop down label can say "Shortcodes" like it did before, and then we can just add our GiveWhen shortcodes to that list.  Other shortcodes from the theme or plugins would just show up in that same list at that point, right?  Unless they happen to be adding their own separate drop-down..??
