### ISSUE TITLE
PayPal ISU Cancel Error

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#45]
I started the PayPal Connect process with ISU, but I closed the mini-browser before logging in to PayPal which cancels the process.  Instead of dropping me back onto the page, though, it gets stuck on this spinner...

![image](https://user-images.githubusercontent.com/629241/29000658-8143e98e-7a37-11e7-889d-575fcfa26fb2.png)

**Comment by tejasm-itpath** [comment]
@angelleye 
Right now I have removed the code that adding spinner from our side.
We have to ask PayPal for the event of the closing of PayPal Lightbox.
PayPal has provided that kind of events in checkout.js but for ISU we have to ask them.
I have looked into the PayPal js files 
https://www.paypal.com/webapps/merchantboarding/js/lib/lightbox/partner.js
and 
https://www.paypal.com/webapps/merchantboarding/js/lib/lightbox/signup.js
But can't find event like they have at the time of paypal configurations.

**Comment by angelleye** [comment]
@tejasm-itpath Did you check the basic sample they sent us previously?

**Comment by tejasm-itpath** [comment]
@angelleye  Yes , we have covered all the js code  that are in the example and PDF file.

**Comment by angelleye** [comment]
@tejasm-itpath okay, so what exactly do you need me to ask PayPal then?

**Comment by tejasm-itpath** [comment]
@angelleye 
For example : checkout js has some good parameters in the JS setup See this link https://developer.paypal.com/docs/classic/express-checkout/in-context/javascript_advanced_settings/
And also have this kind of functions that provide functionality like we can add our own code
https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/upgrade-integration/
```
onCancel: function(data, actions) {
            return actions.redirect();
        }

```
For PayPal ISU we have only this small snippet of JS 
```
<div dir="ltr" style="text-align: left;" trbidi="on">
<script>(function(d, s, id){
 var js, ref = d.getElementsByTagName(s)[0];
 if (!d.getElementById(id)){
 js = d.createElement(s); js.id = id; js.async = true;
 js.src =
"https://www.paypal.com/webapps/merchantboarding/js/lib/lightbox/partner.js"
;
 ref.parentNode.insertBefore(js, ref);
 }
 }(document, "script", "paypal-js"));
</script>
```
So if we can find events similar to checkout.js then it will be a proper way of using PayPal ISU events.

**Comment by angelleye** [comment]
@tejasm-itpath PayPal says there is no cancel method for ISU.  It should just drop them right back where they were if they close the box or cancel.

We're getting stuck on our own spinner message, so we need to somehow catch when that window gets closed and actually send the user back to the settings page.  We must be doing that for the completed process..??  So we just need to do the same for the canceled process.

Also, the message in our spinner needs to be adjusted.  It should say "Please wait for the PayPal login and follow the steps to proceed."

Then when they complete the process it will send them back to settings like it does now, but it should also do the same if they cancel.

**Comment by tejasm-itpath** [comment]
@angelleye 
Right now I have removed the spinner but i am finding a way on the success and on failed or return of the ISU PopUp.
I have to do some mind boosting using JQuery.
