### ISSUE TITLE
Problem with live PayPal ISU / Connect logic..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#47]
When I switch the PayPal Connect toggle to live mode I have two problems...

![image](https://user-images.githubusercontent.com/629241/29000701-52788c70-7a39-11e7-9292-9d4a1cd8a6a2.png)

1)  It's telling me the live is already connected when it's not.
2)  It's giving me client auth errors.

I'm looking at the logic for when the connected message gets output and I see...

```
if ($live_paypal_account_id !== false && $conncet_to_live_paypal_flag == 'Yes') {
    echo '<span class="label label-success">'.__('You are Connected with Live PayPal Environment.','angelleye_give_when').'</span><br><br><br>';
}
else{
    echo '<span class="label label-danger">'.__('You are not Connected with Live PayPal Environment.','angelleye_give_when').'</span><br><br><br>';
}
```

I noticed the misspelled `$conncet_to_live_paypal_flag` variable and was thinking maybe that was the issue.  That's when I discovered the actual variable was indeed misspelled and used that way in code (mentioned in #46).

When I look in the wp_options table I don't see any records with "give_when" in them at all, so I'm a little confused how this is supposed to be working..??

The logic is looking for `$live_paypal_account_id` which is empty right now, so that means `$conncet_to_live_paypal` must be coming back as Yes even though it's not really connected right now.  Again, though, I don't find this in the options table, so I don't know where to clean that setting value..??

**Comment by tejasm-itpath** [comment]
@angelleye 
I still can't reproduce this error but when you pull dev branch
This will be resolved because we have configured API into https://www.angelleye.com/web-services/givewhen/paypal-isu/ Server.

**Comment by angelleye** [comment]
@tejasm-itpath Nope, still not working.

**Comment by angelleye** [comment]
@tejasm-itpath It makes sense that we're seeing the error because we don't have valid credentials entered for live.  It still does not make sense that my site is telling me it's connected when it's not.

**Comment by tejasm-itpath** [comment]
@angelleye  I am really can't reproduce the error.  And If credentials are incorrect or blank then it is displaying Invalid Credentials error

**Comment by angelleye** [comment]
@tejasm-itpath The error being displayed makes sense because credentials are not populated for live account.  However, the message that I'm connected does not make sense. 

I just yesterday gave you a login for woo.angelleye.com (again).

**Comment by tejasm-itpath** [comment]
@angelleye  Yes I have tested in your  woo.angelleye.com 
Can we connect with live and then disconnect it from live and then we check ?
Because I am thinking that you have tested this thing in old version and after that wordpress option is set in database.
I have tested in more than 3-4 WP sites(Old and new wp setup both) but I am not getting that type of error.

**Comment by angelleye** [comment]
@tejasm-itpath That's what confused me even more.  I was trying to find the option in the DB to clear it out and start fresh, but I don't even see it in there.  We'll look at it together over screenshare later.

**Comment by angelleye** [comment]
@tejasm-itpath I'd like to make another adjustment here, too.

I understand we're hitting our angelleye.com service to build the ISU URL for PayPal Connect button, and if this fails then we're getting the error as displayed and the Connect button won't show up.

I'd like to add some error handling for this to provide a better user experience.  Ideally, the service will respond correctly and the PayPal Connect button will be available for use.  However, if the service fails for any reason, then we should simply hide the PayPal Connect button and open the Advanced fields by default so that they copy/paste credentials.

**Comment by angelleye** [comment]
Another issue we have here.  If I use the PayPal Connect button successfully, but then I manually remove the API credentials and save, it still shows that I'm connected.  So again, our logic is not consistent with the possible status.  We need to make sure all fields are populated in order to consider it fully connected.

**Comment by angelleye** [comment]
@tejasm-itpath We also need to consider the scenario where somebody copies and pastes their credentials without using the connect button (regardless of whether the Connect button is an option or not.)  

So if I simply install the plugin and copy / paste my credentials because I don't feel comfortable logging in to the tool, then it needs to show it's connected and ready to go.  Or maybe we could even show a "partially connected" in that case.

**Seems like something we need to discuss over the phone since I have so many notes about this here.**

**Comment by tejasm-itpath** [comment]
@angelleye  Yes sure
