### ISSUE TITLE
PayPal BN Code

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#48]
Need to get our BN code setup for all PayPal API calls in this plugin:  AngellEYE_GiveWhen

**Comment by tejasm-itpath** [comment]
@angelleye 

By default Angell EYE PayPal PHP Library has ButtonSource is "AngellEYE_PHPClass".
We are overwirting that variable with "AngellEYE_GiveWhen" value.
It also reflactes in NVPCredentials string so we are also replcing it.

**Comment by angelleye** [comment]
@tejasm-itpath I think there may be a better way to handle that...

You could have set a variable for our $GiveWhenButtonSource = "AngellEYE_GiveWhen" and then use that variable in all the other files.  That way if the code ever changes we can just update one value

**Comment by tejasm-itpath** [comment]
@angelleye  
Okay I am changing it then
