### ISSUE TITLE
WP Page Templates instead of pages with shortcodes...

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#49]
We've discussed this before.  Not sure if it's already been fixed and I just have leftover content, or what..??

When I look at WP -> Pages right now I'm seeing pages for GiveWhenErrors and GiveWhenThankYou, and those pages have a shortcode inside them for displaying content.

As previously discussed, it's better to do this with page templates and not require an actual page be created in WP because if people delete the page then it breaks things.

**Comment by tejasm-itpath** [comment]
@angelleye 
We already have Page Templates under /templates directory. but page templates needs to be assigned on some page and we can show/redirect to page not it's page templates so we have done similar to WC Vendors and WooCommerce. They have also created page and adding shortcode.

**Comment by angelleye** [comment]
That was their old way, though.  We've had this discussion before.  I need to find the details again but in WC 3.0 they changed the way they're handling all of their pages to a better method that doesn't require pages with shortcodes.  Then the way you would override or customize such pages would be through your theme or your own plugin.

Right now if a user deletes those pages or messes with the shortcode then they won't work.  That's why WooCommerce changed the method, and they have a document somewhere that explains all of this, but I can't find it now.
