### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#5]
We need to build transaction history functionality into the plugin so people can manage all of the transactions that are processed by the plugin.

So for any goal, there should be a Transaction History section where you can see the most recent transactions, search transactions, view details, process refunds, etc.

Within the Transaction History section we can show the current PayPal Balance for the user just so they have a quick reference, and then we also allow them to browse transactions related to that specific goal, search for transactions, view transaction details, and refund transactions.  If refunds occur, these should show up in the transaction history as well.

In #4 we specified all the APIs that would be required for granted permissions in order to build what's explained above.  I've already built a transaction history system like that within our [PayPal Glass](https://github.com/angelleye/paypal-glass) project that was built with our library in Laravel.  You can [see that here](http://paypal-glass.angelleye.com/) for a reference of what I'd like, and you'll notice you can click the transaction ID to see details and refund the transaction.

Data stored in WordPress can be minimal since we'll be pulling most of it from PayPal.  In fact, we may want to utilize the custom field so that we can pull all transaction history via the API and then we wouldn't need to store the transactions in WP database tables at all.  We can discuss this more together.

**Comment by tejasm-itpath** [comment]
@angelleye 
created from issue #6 as we need it first in the flow.
