### ISSUE TITLE
Goal ->My Account tabs for Front end  & User Status Management

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#59]
Right now, the system will only allow a user to sign up for a goal one time.  It will let them sign up for multiple goals, but not the same goal more than once.

In instances where the user has already signed up for a particular goal, we need to consider that they may want to adjust their donation amount.

We're going to need to build a "My Account" section similar to what WooCommerce does.  Inside this the donor will be able to manage their goals: delete agreements, adjust donation amounts, etc.

**Comment by tejasm-itpath** [comment]
@angelleye 
For My Account Section we have discussed on call , But we decided to think on two ways 
While site has WooCommerce installed and Woocommerce not installed 
because woocommerce is giving myaccount section
And then we leave it for future discussion to think about it more in deep.

**Comment by tejasm-itpath** [comment]
@angelleye 
But I think , it would be best if we have our separate tab for "GiveWhen Account".
It will be independent from all the plugin so we can manage it own way with hosted solutions also.
What's  your thoughts on that ?

**Comment by angelleye** [comment]
@tejasm-itpath Yes, right now we need to treat this as a completely stand-alone plugin.  Later we'll build a premium extension to add WooCommerce Compatibility.

So our My Account page should allow the Givers to login, view their existing agreements/goals, and edit them or cancel them.

**Comment by tejasm-itpath** [comment]
@angelleye 
Added Responsive design for My Account Tab 
https://www.screencast.com/t/YPhgvgWm4

**Comment by tejasm-itpath** [comment]
@angelleye 
New Endpoint is added as *givewhen-my-account* 
If you want to run it please deactivate and activate plugin again as endpoints are initializing at the time of Plugin activation.

**Comment by tejasm-itpath** [comment]
Added short code to display login user's registerd goals list 
Shortcode name :  givewhen_my_goals
