### ISSUE TITLE
Thank you page and error page template needs to be adjust according to the theme.

### ISSUE THREAD

**Issue by tejasm-itpath** [angelleye/GiveWhen#61]

**Comment by tejasm-itpath** [comment]
@angelleye 
We have our custom template for Thank you page and error pages. and they are easily overwrite into other themes so user can put their own class and sidebars if they want. according to their requirements.
I looked into other plugins for custom templates , they are also giving only required information in template as we have given in our plugin. and they are generally full width. 
I have tested in BeTheme, DiviTheme and Site Origin themes and it looks good in  every theme.

**Comment by angelleye** [comment]
Okay...I guess I don't remember what this issue was created for..??
