### ISSUE TITLE
Adjustments to existing user / billing agreement sign-ups.

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#63]
As intended, when I sign up for "goal #2" after already signing up for "goal #1" with the same email/account, then it doesn't send me through PayPal again.  It simply uses the existing billing agreement that's on file for the account.  This is good.

The spinner still told me that I was going to be redirected to PayPal, though, so that was a little confusing when I wasn't.  It simply dropped me onto the thank you page instead. This is fine, but we need to guide the user a little bit better when this sort of circumstance comes up.

**Comment by tejasm-itpath** [comment]
@angelleye 
Check this commit  
https://github.com/angelleye/GiveWhen/commit/7883db58401ce6020ff85ddbc727a2f88511b9d2

I have replace all that particular statement to "Processing..." the way PayPal welsite has.
