### ISSUE TITLE
Email didn't get added when running a test as guest..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#64]
I'm putting together a demo video and I noticed that when I view the Giver list the email address did not get included like it should.

![image](https://user-images.githubusercontent.com/629241/29266571-f0233db8-80aa-11e7-8239-848faf5c0af2.png)

I'm wondering if there's a character limit on the field or something that kept it from getting added correctly..??  The email address I used is andrew+testertesterson@angelleye.com.

**Comment by tejasm-itpath** [comment]
@angelleye  I have changed that Giver email Id to the PayPalEmail ID from which PayPal account giver has paid to goal.
check this image https://www.screencast.com/t/QLUDdOTf
