### ISSUE TITLE
Giver -> Transactions table display in admin panel.

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#65]
Right now I can view the Givers list for a goal, and I can also view transactions for a goal, but the transactions page just shows me all transactions for all givers.

From the givers list I should be able to click on an individual Giver to see only their transactions.

**Comment by tejasm-itpath** [comment]
@angelleye 
We already have filter by user name in the list Transactions page for particular goal
see this: https://www.screencast.com/t/JRwgUxXR

Either we can add dropdown on the transactions that lists all the givers's name for that goal
Or Your idea is good too.

**Comment by angelleye** [comment]
A drop down could eventually be full of thousands of giver names.  That would get messy.  It would be best to be able to view the Givers list, search and filter within that, and then simply click the Giver name for the person you want to see transaction history for.
