### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by angelleye** [angelleye/GiveWhen#69]
While playing around with a theme tutorial and creating my own 404 page I noticed this PHP notice when browsing to a page that doesn't exist on my site.

>Notice: Trying to get property of non-object in /home/angelley/sandbox_woocommerce/wp-content/plugins/angelleye-givewhen/public/partials/givewhen-public-display.php on line 29

**Comment by tejasm-itpath** [comment]
@angelleye 
give_when_detect_shortcode function is added only to detect the givewhen shortcode in the page content. It was neccesory when you have to load particular CSS or JS only when shotcode detect.we have Bootstrap design before, but now we have our own cutom class so it will not affect/conflict with other css class. So Right now I am commenting this function.
